version: "3.8"

services: 
  mysql:
    image: mysql:8.0 
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DATABASE=food_db1
    ports: 
      - 3306:3306
    networks:
      - shared-network
    volumes: 
      - ./mySQL_DB/meals.sql:/docker-entrypoint-initdb.d/meals.sql
      
  server:
    container_name: server
    restart: unless-stopped
    image: server-prod:1.0.0
    build: 
      context: server
      target: production
      dockerfile: Dockerfile
    ports: 
      - 4000:4000
    networks:
      - shared-network
    depends_on:
      - mysql

  api:
    container_name: food-order-app
    restart: unless-stopped
    image: food-order-app-prod:1.0.0
    build: 
      context: api
      target: production
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    networks:
      - shared-network
    depends_on:
      - server

    
networks: 
  shared-network:
    driver: bridge

# volumes: 
#   my-db: